server:
  port: 8082
  
  
spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/mini-project12
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    

plan-api:
  messages:
    palnSaveSucc: Record Saved
    planSaveFail: Sorry Not Able to Save Data
    planUpdateSucc: Record Updated
    planUpdateFail: Unable to Update Record
    planDeleteSucc: Record Deleted
    planDeleteFail: Unable to Delete the record
    planStatusSucc: Record Status Changed
    planStatusFail: Unable to Change the Status
    
